### ISSUE TITLE
xiaoACE找bug找到这里来了 :)

### ISSUE THREAD

**Issue by xiaoACE6716** [SNWCreations/JKookTutorial#1]
JKookTutorial第六章的CommandManager#registerArgumentParser的两个KMarkdown链接中的第二个链接地址有误，应该为`https://developer.kookapp.cn/doc/kmarkdown` 而不是 `https://developer.kookapp.cn/docs/kmarkdown`

**Comment by xiaoACE6716** [comment]
![image](https://user-images.githubusercontent.com/94223505/221103079-371a6a1e-b587-405c-840b-c7f363228092.png)

**Comment by xiaoACE6716** [comment]
已发起pr

**Comment by SNWCreations** [comment]
发现了 PR #2 ，已合并。
